modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="trumpetskeleton"
version="${file.jarVersion}"
displayName="Trumpet Skeleton"

authors="JamiesWhiteShirt"

description='''
The sound of trumpets echoes through the night...
'''

[[dependencies.sakurarosea]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
