name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.0

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.8

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v2

        with:
          name: JAR
          path: build/libs/trumpetskeleton-*.jar
